
name: curve_clash_flutter
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.29.0
  flame_audio: ^2.11.5
  flutter_lints: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/audio/sfx/count.wav
    - assets/audio/sfx/go.wav
    - assets/audio/sfx/crash.wav
    - assets/images/curve_clash_logo_offisiell.png
    - assets/images/starfield.png
